ARG ELK_VERSION=6.4.2

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
COPY config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml