version: '2'
services:
  elasticsearch:
          build:
            context: elasticsearch/
            args:
              ELK_VERSION: 6.4.2
          volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ./elasticsearch/data:/usr/share/elasticsearch/data
          ports:
            - "9200:9200"
            - "9300:9300"
          environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
      build:
        context: logstash/
        args:
          ELK_VERSION: 6.4.2
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      ports:
        - "5000:5000"
        - "5000:5000/udp"
        - "9600:9600"
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      depends_on:
        - elasticsearch

  kibana:
      build:
        context: kibana/
        args:
          ELK_VERSION: 6.4.2
      volumes:
        - ./kibana/config/:/usr/share/kibana/config:ro
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
